server:
  port: ${PORT:8012}
  
spring:
  application:
    name: grocery-api

  datasource:
    driverClassName: org.postgresql.Driver
    initialization-mode: NEVER
    password: ${GROCERY_API_PASSWORD}
    url: jdbc:postgresql://${GROCERY_API_URL}:5432/${GROCERY_API_NAME:grocery_api}
    username: ${GROCERY_API_USERNAME}
    
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    generate-ddl: false
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        default_schema: ${GROCERY_API_SCHEMA:public}
    show-sql: false
    
